## [Problem 1] Matrix product is calculated manually

$$A =\begin{bmatrix}-1 & 2 & 3\\
4 & -5 & 6\\7 & 8 & -9\end{bmatrix}$$,$$B =\begin{bmatrix}0 & 2 & 1\\0 & 2 & -8\\2 & 9 & -1\end{bmatrix}$$,
$$AB =\begin{bmatrix}0+0+6 & -2+4+27 & -1+(-16)+(-3)\\0+0+12 & 8+(-10)+54 & 4+40+(-6)\\0+0+(-18) & 14+16+(-81) & 7+(-64)+(-9)\end{bmatrix}$$,$$AB =\begin{bmatrix}6 & 29 & -20\\12 & 52 & 38\\-18 & -51 & -48\end{bmatrix}$$

## [Problem 2] Calculation by NumPy function

In [12]:
#USING MATMUL()
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
ab_ndarray = np.matmul(a_ndarray, b_ndarray)
print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [13]:
#using dot()
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
ab_ndarray = np.dot(a_ndarray, b_ndarray)
print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### [Problem 3] Implementation of calculation of a certain element

1.	Multiply the (0,0) element $a_{0, 0}$ of matrix A with the (0,0) element $b_{0, 0}$ of matrix B

In [14]:
ab = (a_ndarray[0][0]*b_ndarray[0][0])
ab

0

In [10]:
a1 = a_ndarray[0][2]
b1 = b_ndarray[2][0]
a1*b1

6

2.	Multiply the (0,1) element $a_{0, 1}$ of matrix A with the (1,0) element $b_{1, 0}$ of matrix B

In [ ]:
ab = (a_ndarray[0][1]*b_ndarray[1][0])
ab

0

3.	Multiply the (0,2) element $a_{0, 2}$ of matrix A with the (2,0) element $b_{2, 0}$ of matrix B

In [ ]:
ab = (a_ndarray[0][2]*b_ndarray[2][0])
ab

6

4.	Add all those values

In [ ]:
sum_ab = (a_ndarray[0][0]*b_ndarray[0][0])+(a_ndarray[0][1]*b_ndarray[1][0])+(a_ndarray[0][2]*b_ndarray[2][0])

sum_ab

6

#### [Problem 4] Creating a function that performs matrix multiplication

In [ ]:
def product_of_matrix(a, b):
    matrix_ab = np.empty([3,3])
    for row1 in range(a.shape[0]):
        for column1 in range(b.shape[1]):
            matrix_ab[row1][column1] = sum(a[row1, :]*b[:, column1])
    return matrix_ab
print(product_of_matrix(a_ndarray, b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


### [Problem 5] Judge the input whose calculation is not defined

In [15]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
if d_ndarray.shape[0] == e_ndarray.shape[1]:
    print(product_of_matrix(d_ndarray, e_ndarray))
else:
    print("matrices are not aligned")


matrices are not aligned


In [16]:
d_ndarray.shape[0]

2

## [Problem 6] Transposition

In [ ]:
z = d_ndarray.T
print(product_of_matrix(z, e_ndarray))

[[ 33. -28.   9.]
 [-48.  41.  -6.]
 [  9.  -6.  45.]]
